---
- hosts:
    - all
  gather_facts: False
  tasks:
    - name: mail notification for patching
      shell: /home/rbal10/mailscript.sh {{ inventory_hostname }}
      delegate_to: localhost
      register: mailresult
    - debug: msg="{{mailresult.stdout}}"
    - name: Truncate logs
      shell: "/usr/bin/truncate -s 0 /tmp/ansible.log"
      delegate_to: localhost
      run_once: true
    - lineinfile: create=yes dest=/tmp/ansible.log line="{{mailresult.stdout}}" state=present
      delegate_to: localhost
    - lineinfile: 
        path: /tmp/ansible.log
        line: 'Hello Team, Please refer the Patch result below,'
        insertbefore: BOF
      delegate_to: localhost
      run_once: true
    - lineinfile:
        path: /tmp/ansible.log
        line: 'To view the detailed result, login to rundeck portal http://nke-lnx-dis-d111. For any questions/concerns please reach out to lst-techops.unixeng@nike.com'
      delegate_to: localhost
      run_once: true  
    - name: mail
      shell: cat /tmp/ansible.log|mailx -s "patch result" ragul.balakrishnan@nike.com
      delegate_to: localhost
      run_once: true

